### ISSUE TITLE
Change type of enclosing brackets of bind params on app.go

### ISSUE THREAD

**Issue by bruferrari** [novatrixtech/swagger-codegen#2]
In `app.go` when the file is generated by the code gen the params comes enclosed in a brackets like these ones => `{ }` and the macaron API doesn't support it, as an enhancement I'll suggest an implementation of a parser change the `{myObjId}` to `:myObjId` removing the mentioned brackets and adding just the `:` sign, for example.

**Comment by felipeweb** [comment]
@bruferrari is it possible to change /campaigns/{campaignId} to /campaigns/:campaignId on yml file? The codegen just get the path value on yml.

**Comment by jeffprestes** [comment]
No, @felipeweb . Brackets are part of Swagger syntax.

**Comment by bruferrari** [comment]
Unfortunately, it's not possible @felipeweb like @jeffprestes has said before it's part of Swagger syntax, I don't know exactly what kind of mechanism Swagger uses to interpreter YAML/JSON but I think it's worth take a look at it, what do you think?

**Comment by bruferrari** [comment]
@felipeweb Or maybe implement some kind of parser that takes the data inside brackets and put it into `:` when the code is being generated, actually I don't know if it's possible...
