### ISSUE TITLE
Include a string fn on models for logging and debugging 

### ISSUE THREAD

**Issue by bruferrari** [novatrixtech/swagger-codegen#8]
Self-explanatory title.

**Comment by bruferrari** [comment]
@felipeweb just check my last commit [here](https://github.com/novatrixtech/swagger-codegen/blob/feature/model-string-fn/modules/swagger-codegen/src/main/resources/mercurius-go-server/model/model.mustache) and tell me what do you think... I haven't sent a PR yet because I need to do more tests on this function.

@jeffprestes I remember that you've said in the past that you would like to see a function like that for debugging purposes in our nx models, well, here it goes my first real contribution to this project. 😄 

I hope it won't explode anything. 😁

**Comment by felipeweb** [comment]
Good go ahead

**Comment by felipeweb** [comment]
done here https://github.com/novatrixtech/swagger-codegen/commit/3a7fc60cc1d31ff4d85519920ac0346a94ff319c
